.TH sxhkd 1 sxhkd
.SH NAME
Simple X HotKey Daemon.
.SH SYNOPSIS
.SY sxhkd
.RI [ OPTIONS "] [" EXTRA_CONFIG " ...]"
.YS
.SH DESCRIPTION
.PP
sxhkd is a simple X hotkey daemon.
.SH OPTIONS
.TP
.BI -h
Print the synopsis to standard output and exit.
.TP
.BI -v
Print the version information to standard output and exit.
.TP
.BI -c " CONFIG_FILE"
Read the configuration from the given file.
.TP
.BI -r " REDIR_FILE"
Redirect the commands output to the given file.
.SH CONFIGURATION
.PP
Each line of the configuration file is interpreted as so:
.IP \(bu 2
If it starts with
.IR # ,
it is ignored.
.IP \(bu 2
If it starts with one or more white space characters, it is read as a command.
.IP \(bu 2
Otherwise, it is parsed as a hotkey: each key name is separated by spaces and/or
.IR +
characters.
.PP
General Syntax:
.EX
    [MODIFIER + ]*[@|!]KEYSYM
        COMMAND
.EE
.PP
Where
.I MODIFIER
is one of the following names:
.BR super , " hyper", " meta", " alt", " control", " ctrl", " shift", " mode_switch", " lock", " mod1", " mod2", " mod3", " mod4", " mod5" .
.PP
If
.I @
is added at the beginning of the keysym, the command will be run on key release events, otherwise on key press events.
.PP
If
.I !
is added at the beginning of the keysym, the command will be run on motion notify events and must contain two integer conversion specifications which will be replaced by the
.BR x " and " y
coordinates of the pointer relative to the root window referential (the only valid button keysyms for this type of hotkeys are:
.BR button1 ",…, " button5 ).
.PP
If
.I :
is added at the beginning of the keysym, the captured event will be replayed for the other clients.
.PP
The keysym names are those your will get from
.BR xev (1).
.PP
Mouse hotkeys can be defined by using one of the following special keysym names:
.BR button1 ", " button2 ", " button3 ", ..., " button24 .
.PP
The hotkey can contain a sequence of the form
.IR {STRING_1,…,STRING_N} ,
in which case, the command must also contain a sequence with
.I N
elements: the pairing of the two sequences generates
.I N
hotkeys.
.PP
In addition, the sequences can contain ranges of the form
.I A-Z
where
.IR A " and " Z
are alphanumeric characters.
.PP
What is actually executed is
.IB SHELL " -c "
.IR COMMAND ,
which means you can use environment variables in
.IR COMMAND .
.PP
.I SHELL
will be the content of the first defined environment variable in the following list:
.BR SXHKD_SHELL ", " SHELL .
.PP
If
.B sxhkd
receives a
.I SIGUSR1
signal, it will reload its configuration file.
.PP
If no configuration file is specified through the
.B -c
option, the following is used:
.IR $XDG_CONFIG_HOME/sxhkd/sxhkdrc .
.SH AUTHOR
.MT baskerville@lavabit.com
Bastien Dejean
.ME
.SH LINKS
.UR https://github.com/baskerville/sxhkd
Homepage
.UE
